version: '3'

vars:
  VENV_DIR: ./.venv
  PYTHON3: python3
  PYTHON: source {{.VENV_DIR}}/bin/activate && {{.PYTHON3}}
  MAQAMAT_FILE: maqamat.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  directories:
    desc: Create output directories
    cmds:
      - mkdir -p {{.VENV_DIR}}
    status:
      - test -d {{.VENV_DIR}}

  setup-python:
    desc: Setup local Python virtual environment
    deps: [directories]
    cmds:
      - '{{.PYTHON3}} -m venv {{.VENV_DIR}}'
      - '{{.VENV_DIR}}/bin/python3 -m pip install --upgrade pip 1>/dev/null 2>/dev/null'
    status:
      - test -f {{.VENV_DIR}}/bin/activate

  install:
    desc: Install Python dependencies
    deps: [directories, setup-python]
    cmds:
      - '{{.PYTHON}} -m pip install -r ./requirements.txt'
    sources:
      - requirements.txt
    generates:
      - '{{.VENV_DIR}}/lib/**/site-packages/*'

  list:maqamat:
    desc: List all maqam names defined in the YAML file
    cmds:
      - yq '.maqamat | keys | .[]' {{.MAQAMAT_FILE}}

  generate:all:
    desc: Generate all output files for all maqamat defined in the YAML file
    deps: [install]
    cmds:
      - '{{.PYTHON}} ./maqamat.py --generate-scl --maqamat-file {{.MAQAMAT_FILE}}'

  generate:maqam:
    desc: Generate output files for a specific maqam, e.g. task generate:maqam MAQAM=urmawi
    deps: [install]
    preconditions:
      - sh: '[ -n "{{.MAQAM}}" ]'
        msg: "MAQAM variable is required, e.g. task generate:maqam MAQAM=urmawi"
    cmds:
      - '{{.PYTHON}} ./maqamat.py --generate-scl --maqamat-file {{.MAQAMAT_FILE}} --maqam {{.MAQAM}}'

  generate:bracelet-diagram:
    desc: Generate bracelet diagram
    deps: [install]
    cmds:
      - '{{.PYTHON}} ./bracelet_diagram.py'
